### ISSUE TITLE
Alignment Y has no influence

### ISSUE THREAD

**Issue by jvolker** [pixtron/electron-traywindow-positioner#13]
In macOS on a Macbook Pro (running Mojave) without any monitors attached the browser window is always positioned at the bottom of the screen. Alignment Y has no influence. Alignment X works though.

My display settings in case this matters:

![image](https://user-images.githubusercontent.com/546852/80384483-38136d00-88a5-11ea-9866-3b60c583ad91.png)

**Comment by pixtron** [comment]
Could you post a code example @jvolker?

**Comment by pixtron** [comment]
closing this issue as it is stale. if you still experience problems, please open a new issue and provide a public repo where i can reproduce the issue.
